# Generated by Django 5.2.6 on 2025-09-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ano_lancamento', models.IntegerField()),
                ('sinopse', models.TextField()),
                ('atores', models.ManyToManyField(to='app.ator')),
            ],
        ),
    ]
